# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: What is TsFreddie doing?
email: whatis@tsdo.in
description: >- # this means to ignore newlines until "baseurl:"
  TsFreddie's homepage
twitter_username: TsFreddie
github_username: TsFreddie
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: CN # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-polyglot

languages: ["en", "zh-CN"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

author:
  name   : "Freddie W"
  avatar : "https://avatars.githubusercontent.com/u/3797859"
  bio    :
    en: Professional Stuff Maker
    zh-CN: 职业开坑能手
  links:
    en:
      - label: "itch.io"
        icon: "fa-brands fa-itch-io"
        url: "https://tsfreddie.itch.io"
      - label: "Twitter"
        icon: "fa-brands fa-twitter"
        url: "https://twitter.com/tsfreddie"
      - label: "GitHub"
        icon: "fa-brands fa-github"
        url: "https://github.com/TsFreddie"
      - label: "爱发电"
        icon: "fa-solid fa-bolt"
        url: "https://afdian.net/a/tsfreddie"
    zh-CN:
      - label: "itch.io"
        icon: "fa-brands fa-itch-io"
        url: "https://tsfreddie.itch.io"
      - label: "Twitter"
        icon: "fa-brands fa-twitter"
        url: "https://twitter.com/tsfreddie"
      - label: "GitHub"
        icon: "fa-brands fa-github"
        url: "https://github.com/TsFreddie"
      - label: "Ko-Fi"
        icon: "fa-solid fa-mug-hot"
        url: "https://ko-fi.com/tsfreddie"
      - label: "爱发电"
        icon: "fa-solid fa-bolt"
        url: "https://ko-fi.com/tsfreddie"

footer:
  links:
    - label: "itch.io"
      icon: "fa-brands fa-itch-io"
      url: "https://tsfreddie.itch.io"
    - label: "Twitter"
      icon: "fa-brands fa-twitter"
      url: "https://twitter.com/tsfreddie"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/TsFreddie"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
